apiVersion: v2                                                   
publisher: MrLungshot
name: Kotlin-Language-Server
version: 0.0.1     
type: VS Code Extension
displayName: Kotlin
title: Kotlin
description: Kotlin che plugin
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/fwcd/kotlin-language-server.git
category:                                
spec:
  containers:
    - image: "registry.redhat.io/codeready-workspaces/plugin-openshift-rhel8"
      name: crw-ocp-rel8
  extensions:                                                   
    - https://open-vsx.org/api/fwcd/kotlin/0.2.22/file/fwcd.kotlin-0.2.22.vsix
